apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-pipeline-run
  namespace: demo
spec:
  pipelineRef:
    name: springboot-pipeline
  #serviceAccountName: backstage-sa
  # podTemplate:
  #   serviceAccountName: backstage-sa
  params:
    - name: repo_url
      value: "https://github.com/rohit7533/pet-clinic-demo.git"
    - name: image
      value: "idpdeveacr.azurecr.io/pet-clinic-demo:latest"
    - name: deployment_manifest
      value: "/workspace/source/k8s/springboot-deploy.yaml"
    # - name: helm_chart
    #   value: "charts/springboot"
    - name: namespace
      value: "demo"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
