apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: testapp:1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic
spec:
  selector:
    app: pet-clinic
  ports:
    - name: http
      port: 8085
      targetPort: 8080
  type: NodePort
