apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic-demo
  template:
    metadata:
      labels:
        app: pet-clinic-demo
    spec:
      imagePullSecrets:
      - name: registry-auth
      containers:
        - name: pet-clinic-demo
          image: idpdeveacr.azurecr.io/pet-clinic-demo:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-demo
  namespace: demo
spec:
  selector:
    app: pet-clinic-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer